#!/bin/sh

{% include "boot_stub" %}

export broker=$(get_broker)
export zookeeper=$(get_zookeeper)

register_node spawn
startProcess spawn ${HYDRA_CMD} ${broker} ${zookeeper} {{spawn_opt}} ${HYDRA_EXE} spawn etc web
