#!/bin/sh

function fail() {
	echo $1
	exit
}

function register_node() {
	process=$1
	curl -s "${HYDRA_BOOT}/api/register_node?cluster=${CLUSTER_ID}&key=${process}&hostname=${CLUSTER_HOST}"
}

function wait_nodes() {
	process=$1
	curl -s "${HYDRA_BOOT}/api/wait_nodes?cluster=${CLUSTER_ID}&key=${process}"
}

function get_broker() {
	export rabbit=$(wait_nodes rabbit)
	echo "-Dbatch.brokerHost=${rabbit} -Dbatch.brokerPort=5672"
}

function get_zookeeper() {
	export zookeeper=$(wait_nodes zookeeper)
	echo "-Dzk.servers=${zookeeper}:2181"
}

# setup environment
export RUNBIN="${HYDRA_IMAGE}/bin"
export PIDDIR="${HYDRA_IMAGE}/etc/pid"
export HYDRA_JAR="${HYDRA_IMAGE}/lib/hydra.jar"
export PATH="${PATH}:${RUNBIN}"
export COMMON_OPT="{{common_opt}}"
export HYDRA_OPT="-Dhydra.tree.cache.maxSize=250 -Dhydra.tree.page.maxSize=50 -Deps.mem.debug=0"
export LOG4J_OPT="-Dlog4j.defaultInitOverride=true -Dlog4j.configuration=${HYDRA_IMAGE}/etc/log4j.conf"
export JAVA_CMD="java -server ${COMMON_OPT}"
export HYDRA_CMD="${JAVA_CMD} ${LOG4J_OPT} ${HYDRA_OPT}"
export HYDRA_EXE="-jar ${HYDRA_JAR}"

# require hydra.jar
[ ! -f ${HYDRA_JAR} ] && fail "missing hydra exec jar @ ${HYDRA_JAR}"

# pull in hydra properties if they exist
if [ -f ${HYDRA_IMAGE}/etc/hydra.properties ]; then
	CMD_ADD=$(grep = ${HYDRA_IMAGE}/etc/hydra.properties | while read one; do echo "-D${one}"; done)
	export JAVA_CMD="${JAVA_CMD} ${CMD_ADD}"
	export HYDRA_CMD="${HYDRA_CMD} ${CMD_ADD}"
fi

# flcow (copy-on-write) support for 64 bit linux & os x
case $(uname) in
	Linux)
		export LD_PRELOAD=${HYDRA_IMAGE}/lib/libflcow.so:${LD_PRELOAD}
		;;
	Darwin)
		export LD_PRELOAD=${HYDRA_IMAGE}/lib/libflcow.dylib:${LD_PRELOAD}
		;;
esac
export FLCOW_PATH="^${HYDRA_IMAGE}"
export FLCOW_EXCLUDE="\.((stats)|(pid)|(done)|(complete))$"

function setWorkingDir() {
	cd ${HYDRA_IMAGE}
}

function testIsRunning() {
	PIDFILE=$1
	[ ! -f ${PIDFILE} ] && return 0
	PIDVAL=$(cat ${PIDFILE})
	if [ -d /proc ]; then
		[ -d /proc/${PIDVAL} ] && return 1
	else
		EXIST="$(ps ax | grep -v grep | grep ${PIDVAL})" 
		[ "${EXIST}" != "" ] && return 1
	fi
	return 0
}

function startProcess() {
	export PROCNAME=$1; shift
	cd ${HYDRA_IMAGE}
	PID="${PIDDIR}/pid.${PROCNAME}"
	LOG=log/${PROCNAME}.log
	testIsRunning ${PID}
	running=$?
	if [ ${running} -eq 0 ]; then
		echo "startProcess :: ${PROCNAME}"
		nohup $* > ${LOG} 2>&1 &
		echo "$!" > "${PID}"
		echo "started ${PROCNAME}"
		return 0
	else
		return 1
	fi
}

function stopProcess() {
	echo "stopProcess :: $*"
	cd ${HYDRA_IMAGE}
	for process in $*; do
		if [ -f ${PIDDIR}/pid.${process} ]; then
			PID=$(cat ${PIDDIR}/pid.${process})
			tries=1
			if [ -d /proc ]; then
				# in linux, use /proc filesystem. yay
				while [ -d /proc/${PID} ]; do
					echo "stopping ${process} #${tries}"
					[ ${tries} -gt 5 ] && SIG="-9"
					kill ${SIG} ${PID} # 2>/dev/null
					[ ${tries} -gt 1 ] && sleep 1 || usleep 250000
					tries=$((tries+1))
				done
			else
				# everywhere else, use ps. booo
				SIG=""
				EXIST="$(ps ax | grep -v grep | grep ${PID})" 
				while [ "$(ps a | grep -v grep | grep ${PID})" != "" ]; do
					echo "stopping ${process} #${tries} @ ${PID}"
					[ ${tries} -gt 5 ] && SIG="-9"
					kill ${SIG} ${PID} 2>/dev/null || break
					[ ${tries} -gt 1 ] && sleep 1 || sleep 1
					tries=$((tries+1))
				done
			fi
			rm ${PIDDIR}/pid.${process}
		fi
	done
}

