#!/bin/sh

function fail() {
	echo $1
	exit
}

export JAVA=$(which java)
[ -z "${JAVA}" ] && fail "missing java binaries"
[ -z "${HOME}" ] && fail "missing HOME environment variable"
[ ! -d "${HOME}" ] && fail "invalid HOME directory: ${HOME}"
[ -z "${HYDRA_BOOT}" ] && echo "defaulting HYDRA_BOOT" && export HYDRA_BOOT="{{boothost}}"
[ -z "${HYDRA_IMAGE}" ] && echo "defaulting HYDRA_IMAGE" && export HYDRA_IMAGE=${HOME}/hydra
[ -z "${CLUSTER_ID}" ] && export CLUSTER_ID="{{cluster}}"
[ -z "${CLUSTER_HOST}" ] && export CLUSTER_HOST="{{hostname}}"
[ -z "${CLUSTER_HOST}" ] && export CLUSTER_HOST=$(hostname)

# chain boot with cluster and host set properly
bash <(curl -s "http://${HYDRA_BOOT}/render/boot-two?cluster=${CLUSTER_ID}&hostname=${CLUSTER_HOST}")

