#!/bin/sh

[ -z "${CLUSTER_HOST}" ] && export CLUSTER_HOST="{{hostname}}"
[ -z "${IMAGEVERSION}" ] && export IMAGEVERSION="{{version}}"
[ -z "${PROCESSES}" ] && export PROCESSES="{{process}}"
[ -z "${CLUSTER_HOST}" ] && fail "missing CLUSTER_HOST environment variable"
[ -z "${CLUSTER_ID}" ] && fail "missing CLUSTER_ID environment variable"
[ -z "${PROCESSES}" ] && fail "missing PROCESSES environment variable"

# create required directories
for dir in bin lib log etc/pid; do
	dir=${HYDRA_IMAGE}/${dir}
	[ ! -d ${dir} ] && mkdir -p ${dir} && echo "created ${dir}"
done

# check for updates to required images
for image in bin/hcl bin/job-task.sh etc/log4j.conf lib/hydra.jar lib/libflcow.dylib lib/libflcow.so web.zip; do
	local=${HYDRA_IMAGE}/${image}
	remote=${HYDRA_BOOT}/image/${IMAGEVERSION}/${image}
	[ ! -f ${local} ] && (
		echo "fetching $image..."
		curl -s ${remote} > ${local} || fail "failed image load '${image}'"
	)
done

# unzip web directory
(
	cd $HYDRA_IMAGE
	[ ! -d web ] && unzip web.zip
)

# launch host local processes
for proc in ${PROCESSES}; do
	echo -n "fetching ${proc} boot... "
	bash <(curl -s "${HYDRA_BOOT}/render/boot-${proc}?cluster=${CLUSTER_ID}&hostname=${CLUSTER_HOST}")
done

