#!/bin/bash

[ -z "${HYDRA_BOOT}" ] && export HYDRA_BOOT="{{boothost}}"
[ -z "${CLUSTER_ID}" ] && export CLUSTER_ID={{cluster}}
[ -z "${CLUSTER_HOST}" ] && export CLUSTER_HOST={{hostname}}
[ -z "${HYDRA_IMAGE}" ] && export HYDRA_IMAGE=$(dirname $(dirname $0))
[ -z "${HYDRA_HOST}" ] && export HYDRA_HOST=localhost
[ -z "${HYDRA_AUTH}" ] && export HYDRA_AUTH={{authkey}}

# add hydra bin dir to path so processes can inherit
export PATH=${PATH}:${HYDRA_IMAGE}/bin

exec bash <(curl -s "http://${HYDRA_BOOT}/render/proc?cluster=${CLUSTER_ID}&hostname=${CLUSTER_HOST}") $*
