#!/bin/bash

[ -z "${HYDRA_BOOT}" ] && export HYDRA_BOOT="hydra-boot:8008"
[ -z "${CLUSTER_ID}" ] && export CLUSTER_ID={{cluster}}
[ -z "${CLUSTER_HOST}" ] && export CLUSTER_HOST={{hostname}}
[ -z "${HYDRA_IMAGE}" ] && export HYDRA_IMAGE=$(dirname $(dirname $0))
[ -z "${HYDRA_HOST}" ] && export HYDRA_HOST=localhost

# add hydra bin dir to path so processes can inherit
export PATH=${PATH}:${HYDRA_IMAGE}/bin

bash <(curl -s "http://${HYDRA_BOOT}/render/proc?cluster=${CLUSTER_ID}&hostname=${CLUSTER_HOST}") $*

