#!/bin/sh

{% include "proc-stub" %}

export broker=$(get_broker)
export zookeeper=$(get_zookeeper)

register_node spawn
startProcess spawn ${HYDRA_CMD} ${broker} ${zookeeper} {{ spawn.cmdline }} ${HYDRA_EXE} spawn etc web && (
while [ /bin/true ]; do
	echo "waiting for spawn to come up ..."
	sleep 1
	curl 'http://localhost:5050/command.put' --data 'label=default-task&auth={{ defaults.authkey }}&owner=install&cpu=1&mem=512&io=1&command=hcl task job.conf {% raw %}{{nodes}} {{node}} {{jobid}}{% endraw %}' >/dev/null 2>&1 && break
done
)
