#!/bin/sh

{% include "proc-stub" %}

export zookeeper=$(wait_nodes zookeeper)

register_node qworker
startProcess qworker ${HYDRA_CMD} {{ qworker.cmdline }} ${HYDRA_EXE} mqworker server 5101 ${HYDRA_IMAGE} ${CLUSTER_HOST}:5100
