#!/bin/sh

{% include "proc-stub" %}

export broker=$(get_broker)
export zookeeper=$(get_zookeeper)
export spawn=$(wait_nodes spawn)

register_node minion
startProcess minion ${HYDRA_CMD} ${broker} ${zookeeper} {{ minion.cmdline }} ${HYDRA_EXE} minion minion
