#!/bin/sh

{% include "proc-stub" %}

[ ! $(which rabbitmq-server) ] && fail "missing rabbitmq-server executable"
startProcess rabbit {{ rabbit.start || "rabbitmq-server" }} && (
while [ /bin/true ]; do
	{% autoescape false %} {{ rabbit.check || "rabbitmqctl status >/dev/null 2>&1" }} {% endautoescape %} && break
	sleep 1
	echo "waiting for rabbit to start"
done
)
register_node rabbit
