#!/bin/sh

{% include "proc-stub" %}

setWorkingDir
if [ ! -d mesh ]; then
	(
		echo "creating mesh data directory"
		mkdir mesh && cd mesh
		ln -s ../minion/ job
		ln -s ../log/ log
	)
fi
register_node mesh
export meshes=$(wait_nodes mesh)
export peers=$(
x=0
[ ! -z "${meshes}" ] && for peer in ${meshes}; do
	[ $x -gt 0 ] && echo -n ","
	echo -n ${peer}:{{ mesh.port|| 5000}}
	x=$((x+1))
done
)
echo "found peering mesh nodes: ${peers}"
startProcess mesh ${HYDRA_CMD} {{ mesh.cmdline }} ${HYDRA_EXE} mesh server {{ mesh.port||5000 }} mesh ${peers}
