#!/bin/sh

{% include "proc-stub" %}

setWorkingDir
if [ ! -d mesh ]; then
	(
		echo "creating mesh data directory"
		mkdir mesh && cd mesh
		ln -s ../minion/ job
		ln -s ../log/ log
	)
fi
register_node mesh
startProcess mesh ${HYDRA_CMD} {{ mesh.cmdline }} ${HYDRA_EXE} mesh server {{ mesh.port||5000 }} mesh
