#!/bin/sh

{% include "proc-stub" %}

[ ! $(which rabbitmq-server) ] && fail "missing rabbitmq-server executable"
startProcess rabbit {{ rabbit.server || rabbitmq-server }} && (
while [ /bin/true ]; do
	{{ rabbit.cmd_control || rabbitmqctl }} status >/dev/null 2>&1 && break
	sleep 1
	echo "waiting for rabbit to start"
done
)
register_node rabbit
