#!/bin/sh

{% include "proc-stub" %}

echo "-----(( task-clone ))-----(( $* ))-----(( $(pwd) ))-----"

nodex=$(which node)
[ -z "${nodex}" ] && echo "missing node" && exit 1

conf=$1
nodes=$2
nodenum=$3
jobid=$4

[ ! -f "${conf}" ] && echo "missing config : ${conf}" && exit 1
[ -z ${nodes} ] && echo "missing node count" && exit 1
[ -z ${nodenum} ] && echo "missing node number" && exit 1
[ -z ${jobid} ] && echo "missing job id" && exit 1

cat > job.node.js << EOF
var fs = require('fs');
var cfg = eval('('+fs.readFileSync('${conf}')+')');
if (cfg.hosts) {
	for (var i in cfg.hosts) {
		console.log(['rsync -av --delete ',cfg.hosts[i],':',(cfg.minionDir || 'hydra/minion'),'/${jobid}/${nodenum}/gold/ ./'].join(''));
	}
}
process.exit()
EOF

${nodex} job.node.js > job.bash
bash job.bash

